services:
  - type: cron
    name: pmanager-scraper
    env: node
    schedule: "0 */6 * * *"
    buildCommand: npm install && npx playwright install --with-deps chromium
    startCommand: node scrape-all-with-details.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TEST_USERNAME
        sync: false
      - key: TEST_PASSWORD
        sync: false
      - key: GOOGLE_SPREADSHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
