services:
  - type: web
    name: pmanager-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
      - key: TEST_USERNAME
        sync: false
      - key: TEST_PASSWORD
        sync: false
      - key: GOOGLE_SPREADSHEET_ID
        sync: false
      - key: CRON_SECRET_KEY
        generateValue: true
